### ISSUE TITLE
Dropdown menu is clickable even if it's closed

### ISSUE THREAD

**Issue by avipunes** [fireship-io/226-css-theme-toggler#1]
I tried to create a PR but I don't have permissions  😕

the issue:
https://media.giphy.com/media/PhTjbkLmtw4w59NsGY/giphy.mp4

potential solution:

```css
.has-dropdown .dropdown {
    pointer-events: none;
}
```
